### ISSUE TITLE
"songvol","sevol"変数の追加

### ISSUE THREAD

**Issue by nyoro-wrl** [AioiLight/Open-Taiko-Chart#6]
tciに追加。
曲と効果音の音量調整。
tjaにおけるSONGVOL: SEVOL:と同じものです。
### 例
```
"songvol": 80,
"sevol": 100,
```

**Comment by AioiLight** [comment]
曲や効果音の音量を、譜面ファイルから設定できるようにするつもりはありません。以下はその理由です

### 音量はユーザー、または再生ソフトが決めるべき
YouTubeやニコニコ動画と同じく、ユーザーが音量を決めるべきであるから。譜面自体が音量を決めるのは不適

### 音量を 0dB を超えてブーストしてはいけない

100以上のSONGVOL、SEVOLを指定すると音量を増幅させて再生するソフトがありますが 0dBを超える音量の増幅を行うと音がゆがむ。
